#!/usr/bin/env bash
#
# setup-security-idempotent.sh
# Idempotent security hardening for Ubuntu/Debian
# Safe to re-run multiple times / on multiple servers
#
# Still requires: already have SSH key auth working!

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Starting idempotent security hardening${NC}"
echo ""

# ────────────────────────────────────────────────
# 1. Install packages if missing
# ────────────────────────────────────────────────
echo -e "${GREEN}→ Ensuring required packages are installed...${NC}"
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -yqq --no-install-recommends \
    ufw fail2ban openssh-server

# ────────────────────────────────────────────────
# 2. UFW – only add rules if missing, enable only if inactive
# ────────────────────────────────────────────────
echo -e "${GREEN}→ Configuring UFW (idempotently)...${NC}"

# Allow SSH – prefer profile, fallback to port
if ! ufw status | grep -qE "(OpenSSH|22/tcp)"; then
    if ufw app list | grep -q OpenSSH; then
        ufw allow OpenSSH || ufw allow 22/tcp
    else
        ufw allow 22/tcp
    fi
    echo "  Added SSH allow rule"
else
    echo "  SSH already allowed"
fi

ufw default deny incoming   || true
ufw default allow outgoing  || true

# Enable only if not already active
if ! ufw status | grep -q "Status: active"; then
    echo "y" | ufw enable
    echo "  UFW enabled"
else
    echo "  UFW already active"
fi

ufw reload
echo -e "${GREEN}UFW status:${NC}"
ufw status verbose | head -n 12   # show top part

# ────────────────────────────────────────────────
# 3. SSH hardening – use drop-in if possible, check before write
# ────────────────────────────────────────────────
echo -e "${GREEN}→ Hardening SSH (idempotently)...${NC}"

SSHD_DROPIN="/etc/ssh/sshd_config.d/99-security.conf"

if [[ -d "/etc/ssh/sshd_config.d" ]]; then
    # Modern drop-in style – only write if missing or different
    if [[ ! -f "$SSHD_DROPIN" ]] || ! grep -q "PasswordAuthentication no" "$SSHD_DROPIN"; then
        cat > "$SSHD_DROPIN" << 'EOF'
# Security hardening - generated by setup script
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin prohibit-password
EOF
        echo "  Wrote SSH drop-in config"
    else
        echo "  SSH drop-in already hardened"
    fi
else
    # Legacy: edit main file carefully
    for setting in \
        "PasswordAuthentication no" \
        "KbdInteractiveAuthentication no" \
        "PermitRootLogin prohibit-password"; do
        key="${setting%% *}"
        if ! grep -qE "^${key}\s" /etc/ssh/sshd_config; then
            echo "$setting" >> /etc/ssh/sshd_config
            echo "  Added: $setting"
        fi
    done
fi

# Optional extras (always append if missing)
for extra in \
    "LoginGraceTime 30" \
    "MaxAuthTries 4"; do
    if ! grep -qE "^${extra%% *}\s" /etc/ssh/sshd_config; then
        echo "$extra" >> /etc/ssh/sshd_config
    fi
done

systemctl restart ssh || systemctl restart sshd

# ────────────────────────────────────────────────
# 4. Fail2Ban – only create/override if needed
# ────────────────────────────────────────────────
echo -e "${GREEN}→ Configuring Fail2Ban (idempotently)...${NC}"

JAIL_LOCAL="/etc/fail2ban/jail.local"

if [[ ! -f "$JAIL_LOCAL" ]] || ! grep -q "\[sshd\]" "$JAIL_LOCAL"; then
    cat > "$JAIL_LOCAL" << 'EOF'
[DEFAULT]
bantime  = 4h
findtime = 10m
maxretry = 5
backend  = systemd

[sshd]
enabled   = true
port      = ssh
filter    = sshd
logpath   = %(sshd_log)s
mode      = aggressive
maxretry  = 3
findtime  = 10m
bantime   = 24h
EOF
    echo "  Created jail.local with aggressive SSH protection"
else
    echo "  Fail2Ban jail.local already exists – skipping overwrite"
fi

systemctl restart fail2ban || true
systemctl enable fail2ban --quiet || true

echo -e "${GREEN}Fail2Ban status (sshd jail):${NC}"
fail2ban-client status sshd 2>/dev/null || echo "  (jail not yet active or error)"

# ────────────────────────────────────────────────
# Summary
# ────────────────────────────────────────────────
echo ""
echo -e "${GREEN}Security hardening completed (idempotent run)${NC}"
echo "Re-running this script is now safe."
echo ""
echo "Quick checks:"
echo "  ufw status verbose"
echo "  sshd -T | grep -iE 'password|permitroot|kbd'"
echo "  fail2ban-client status sshd"
echo ""

exit 0
