#!/usr/bin/env bash
#
# secure-ubuntu-2026.sh
# Idempotent Ubuntu/Debian security hardening + auto-start services

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Starting security setup (idempotent + auto-start 2026 edition)${NC}\n"

# ────────────────────────────────────────────────
# Install if missing
# ────────────────────────────────────────────────
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -yqq --no-install-recommends \
    ufw fail2ban openssh-server python3-systemd

# ────────────────────────────────────────────────
# UFW (idempotent)
# ────────────────────────────────────────────────
if ! ufw status | grep -qE "(OpenSSH|22/tcp)"; then
    ufw allow OpenSSH 2>/dev/null || ufw allow 22/tcp
    echo "  → SSH allowed in UFW"
fi

ufw default deny incoming  || true
ufw default allow outgoing || true

if ! ufw status | grep -q "Status: active"; then
    echo "y" | ufw enable
    echo "  → UFW enabled"
else
    ufw reload
fi

echo -e "${GREEN}UFW ready:${NC}"
ufw status | head -n 8

# ────────────────────────────────────────────────
# SSH hardening (drop-in preferred)
# ────────────────────────────────────────────────
SSHD_DROPIN="/etc/ssh/sshd_config.d/99-security.conf"

# FIX: Added spaces around parentheses and simplified the logic for readability
if [[ -d "/etc/ssh/sshd_config.d" ]]; then
    if [[ ! -f "$SSHD_DROPIN" ]] || ! grep -q "PasswordAuthentication no" "$SSHD_DROPIN"; then
        cat > "$SSHD_DROPIN" << 'EOF'
# Security hardening - generated by setup script
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin prohibit-password
EOF
        systemctl restart ssh || systemctl restart sshd || true
        echo "  → SSH hardened (drop-in created/updated)"
    else
        echo "  → SSH already hardened (drop-in up to date)"
    fi
else
    echo "  → SSH drop-in directory not present; skipping drop-in config."
fi

# ────────────────────────────────────────────────
# Fail2Ban – clean drop-in + force start
# ────────────────────────────────────────────────
echo -e "${GREEN}Configuring Fail2Ban...${NC}"

mkdir -p /etc/fail2ban/jail.d

cat > /etc/fail2ban/jail.d/sshd-aggressive.conf << 'EOF'
[sshd]
enabled   = true
port      = ssh
filter    = sshd
backend   = systemd
mode      = aggressive
maxretry  = 3
findtime  = 10m
bantime   = 24h
EOF

# Optional global fallback
if [[ ! -f /etc/fail2ban/jail.local ]] || ! grep -q "backend" /etc/fail2ban/jail.local; then
    echo -e "[DEFAULT]\nbackend = systemd" >> /etc/fail2ban/jail.local 2>/dev/null || true
fi

systemctl daemon-reload
systemctl enable fail2ban --quiet || true
systemctl restart fail2ban || true

# Give the service a moment to initialize the socket
sleep 2

# ────────────────────────────────────────────────
# Fail2Ban diagnostics
# ────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}Fail2Ban diagnostics:${NC}"

if [[ -S /var/run/fail2ban/fail2ban.sock ]]; then
    echo -e "${GREEN}OK: Socket exists → server is running${NC}"
    fail2ban-client status sshd 2>/dev/null || echo "  (sshd jail query issue – check logs)"
else
    echo -e "${RED}Socket MISSING → fail2ban-server not running${NC}"
fi

echo ""
echo "systemctl status fail2ban (top lines):"
systemctl status fail2ban --no-pager | head -n 12 || true

echo -e "\n${GREEN}Script finished. Review output above.${NC}\n"

exit 0
